name: Deploy Leaderboard Project

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Example: Sync your frontend files to S3
    - name: Deploy frontend to S3
      run: |
        aws s3 sync ./frontend s3://your-s3-bucket-name --delete

    # (Optional) Deploy Lambda functions using SAM or ZIP
    - name: Deploy Lambda function
      run: |
        zip -r function.zip backend/
        aws lambda update-function-code \
          --function-name SubmitScoreFn \
          --zip-file fileb://function.zip
